/**
 * Hand-curated fixtures for the instructor design preview. Every value is
 * deliberately realistic: Egyptian instructor + student names, radiology
 * course titles in Arabic, EGP amounts in plausible price bands, rating
 * distributions that match a real teaching feed.
 *
 * Tweaks panel toggles in `tweaks-context.tsx` slice / mutate this fixture
 * at render time so the same data file can produce empty / populated /
 * status-filtered states without round-tripping a backend.
 */

import type {
  EarningsMonth,
  InstructorCourse,
  InstructorEnrollmentEvent,
  InstructorQuestion,
  InstructorReview,
  InstructorStudent,
  PayoutRecord,
} from './types';

export const INSTRUCTOR_PROFILE = {
  id: 'instructor-mock',
  name: 'د. سامي حسن',
  email: 'sami.hassan@radlog.eg',
  avatar: null as string | null,
  specialty: 'استشاري أشعة تشخيصية',
  university: 'كلية الطب — جامعة القاهرة',
  bio: 'استشاري أشعة تشخيصية بخبرة 18 عاماً في تدريس طلاب وأطباء الامتياز. متخصص في أشعة الدماغ والصدر.',
  studentsCount: 5_842,
  coursesCount: 6,
  rating: 4.8,
};

/* ============================== Courses ============================== */

export const MOCK_COURSES: InstructorCourse[] = [
  {
    id: 'c-101',
    slug: 'radiology-foundations',
    title: 'أساسيات الأشعة التشخيصية',
    status: 'published',
    thumbnail: null,
    price: 999,
    studentsCount: 1_247,
    rating: 4.8,
    reviewsCount: 318,
    totalLessons: 42,
    totalDurationMinutes: 720,
    completionPercent: 64,
    earnings: 1_245_753,
    earningsThisMonth: 87_400,
    viewsThisMonth: 4_312,
    createdAt: '2025-09-12T08:00:00.000Z',
    lastEditedAt: '2026-04-21T14:22:00.000Z',
    rejectionReason: null,
    modules: [
      {
        id: 'm-1',
        title: 'مقدمة في علم الأشعة',
        order: 1,
        lessons: [
          { id: 'l-1', title: 'تاريخ الأشعة وتطورها', kind: 'video', durationSeconds: 600, order: 1 },
          { id: 'l-2', title: 'التعرف على الأجهزة الأساسية', kind: 'video', durationSeconds: 720, order: 2 },
          { id: 'l-3', title: 'اختبار قصير: الأساسيات', kind: 'quiz', durationSeconds: 0, order: 3 },
        ],
      },
      {
        id: 'm-2',
        title: 'مبادئ الأشعة السينية',
        order: 2,
        lessons: [
          { id: 'l-4', title: 'الفيزياء وراء الأشعة السينية', kind: 'video', durationSeconds: 900, order: 1 },
          { id: 'l-5', title: 'تفسير صور الصدر', kind: 'video', durationSeconds: 1080, order: 2 },
        ],
      },
    ],
  },
  {
    id: 'c-102',
    slug: 'mri-brain',
    title: 'الرنين المغناطيسي للدماغ',
    status: 'published',
    thumbnail: null,
    price: 1499,
    studentsCount: 892,
    rating: 4.9,
    reviewsCount: 214,
    totalLessons: 36,
    totalDurationMinutes: 600,
    completionPercent: 71,
    earnings: 1_338_708,
    earningsThisMonth: 124_900,
    viewsThisMonth: 3_117,
    createdAt: '2025-11-04T08:00:00.000Z',
    lastEditedAt: '2026-04-29T09:10:00.000Z',
    rejectionReason: null,
    modules: [],
  },
  {
    id: 'c-103',
    slug: 'chest-ct',
    title: 'الأشعة المقطعية للصدر',
    status: 'published',
    thumbnail: null,
    price: 1199,
    studentsCount: 1_402,
    rating: 4.7,
    reviewsCount: 387,
    totalLessons: 48,
    totalDurationMinutes: 840,
    completionPercent: 58,
    earnings: 1_682_398,
    earningsThisMonth: 71_200,
    viewsThisMonth: 5_984,
    createdAt: '2025-07-22T08:00:00.000Z',
    lastEditedAt: '2026-03-17T11:45:00.000Z',
    rejectionReason: null,
    modules: [],
  },
  {
    id: 'c-104',
    slug: 'pediatric-radiology',
    title: 'أشعة الأطفال',
    status: 'pending_review',
    thumbnail: null,
    price: 899,
    studentsCount: 0,
    rating: 0,
    reviewsCount: 0,
    totalLessons: 24,
    totalDurationMinutes: 360,
    completionPercent: 0,
    earnings: 0,
    earningsThisMonth: 0,
    viewsThisMonth: 0,
    createdAt: '2026-04-12T08:00:00.000Z',
    lastEditedAt: '2026-04-30T16:02:00.000Z',
    rejectionReason: null,
    modules: [],
  },
  {
    id: 'c-105',
    slug: 'abdominal-ultrasound',
    title: 'الموجات فوق الصوتية للبطن',
    status: 'draft',
    thumbnail: null,
    price: 799,
    studentsCount: 0,
    rating: 0,
    reviewsCount: 0,
    totalLessons: 12,
    totalDurationMinutes: 180,
    completionPercent: 0,
    earnings: 0,
    earningsThisMonth: 0,
    viewsThisMonth: 0,
    createdAt: '2026-04-25T08:00:00.000Z',
    lastEditedAt: '2026-05-01T08:30:00.000Z',
    rejectionReason: null,
    modules: [],
  },
  {
    id: 'c-106',
    slug: 'musculoskeletal-imaging',
    title: 'أشعة العظام والمفاصل',
    status: 'rejected',
    thumbnail: null,
    price: 1099,
    studentsCount: 0,
    rating: 0,
    reviewsCount: 0,
    totalLessons: 30,
    totalDurationMinutes: 480,
    completionPercent: 0,
    earnings: 0,
    earningsThisMonth: 0,
    viewsThisMonth: 0,
    createdAt: '2026-03-08T08:00:00.000Z',
    lastEditedAt: '2026-04-02T13:14:00.000Z',
    rejectionReason:
      'الوحدة الثانية تحتاج مراجعة لجودة الصوت في الدروس 4 و 7. أعد رفعها بعد تحسين العزل.',
    modules: [],
  },
];

/* ============================== Activity ============================== */

export const MOCK_RECENT_ENROLLMENTS: InstructorEnrollmentEvent[] = [
  {
    id: 'e-1',
    studentName: 'نور عبدو',
    studentAvatar: null,
    courseId: 'c-101',
    courseTitle: 'أساسيات الأشعة التشخيصية',
    enrolledAt: '2026-05-01T09:42:11.000Z',
    pricePaid: 999,
  },
  {
    id: 'e-2',
    studentName: 'محمد إبراهيم',
    studentAvatar: null,
    courseId: 'c-102',
    courseTitle: 'الرنين المغناطيسي للدماغ',
    enrolledAt: '2026-05-01T08:11:00.000Z',
    pricePaid: 1499,
  },
  {
    id: 'e-3',
    studentName: 'سارة طارق',
    studentAvatar: null,
    courseId: 'c-103',
    courseTitle: 'الأشعة المقطعية للصدر',
    enrolledAt: '2026-04-30T22:18:00.000Z',
    pricePaid: 1199,
  },
  {
    id: 'e-4',
    studentName: 'خالد جمال',
    studentAvatar: null,
    courseId: 'c-101',
    courseTitle: 'أساسيات الأشعة التشخيصية',
    enrolledAt: '2026-04-30T19:50:00.000Z',
    pricePaid: 999,
  },
  {
    id: 'e-5',
    studentName: 'ريم شعبان',
    studentAvatar: null,
    courseId: 'c-102',
    courseTitle: 'الرنين المغناطيسي للدماغ',
    enrolledAt: '2026-04-30T15:32:00.000Z',
    pricePaid: 1499,
  },
  {
    id: 'e-6',
    studentName: 'عمر السيد',
    studentAvatar: null,
    courseId: 'c-103',
    courseTitle: 'الأشعة المقطعية للصدر',
    enrolledAt: '2026-04-30T11:04:00.000Z',
    pricePaid: 1199,
  },
];

export const MOCK_RECENT_REVIEWS: InstructorReview[] = [
  {
    id: 'r-1',
    studentName: 'منى عبد الفتاح',
    studentAvatar: null,
    courseId: 'c-102',
    courseTitle: 'الرنين المغناطيسي للدماغ',
    rating: 5,
    comment:
      'أفضل كورس رنين مغناطيسي تابعته في حياتي. الشرح متسلسل والصور مرتبة بطريقة سهلة الفهم.',
    createdAt: '2026-05-01T07:22:00.000Z',
  },
  {
    id: 'r-2',
    studentName: 'أحمد فاروق',
    studentAvatar: null,
    courseId: 'c-101',
    courseTitle: 'أساسيات الأشعة التشخيصية',
    rating: 5,
    comment: 'الأمثلة الإكلينيكية في الوحدة الثالثة كانت ممتازة. شكراً يا دكتور.',
    createdAt: '2026-04-30T20:01:00.000Z',
  },
  {
    id: 'r-3',
    studentName: 'ياسمين ممدوح',
    studentAvatar: null,
    courseId: 'c-103',
    courseTitle: 'الأشعة المقطعية للصدر',
    rating: 4,
    comment: 'محتوى ممتاز لكن جودة الصوت في بعض الدروس تحتاج تحسين.',
    createdAt: '2026-04-30T13:45:00.000Z',
  },
  {
    id: 'r-4',
    studentName: 'بسمة طلعت',
    studentAvatar: null,
    courseId: 'c-101',
    courseTitle: 'أساسيات الأشعة التشخيصية',
    rating: 5,
    comment: 'استفدت كتير من الكورس قبل امتحان الزمالة.',
    createdAt: '2026-04-29T18:20:00.000Z',
  },
];

export const MOCK_PENDING_QUESTIONS: InstructorQuestion[] = [
  {
    id: 'q-1',
    studentName: 'كريم وحيد',
    studentAvatar: null,
    courseId: 'c-102',
    courseTitle: 'الرنين المغناطيسي للدماغ',
    lessonTitle: 'تسلسلات DWI و ADC',
    question: 'ممكن توضح الفرق بين قيم ADC في السكتة الحادة والمزمنة بمثال عملي؟',
    askedAt: '2026-05-01T08:55:00.000Z',
    answered: false,
  },
  {
    id: 'q-2',
    studentName: 'هبة محمود',
    studentAvatar: null,
    courseId: 'c-101',
    courseTitle: 'أساسيات الأشعة التشخيصية',
    lessonTitle: 'تفسير صور الصدر',
    question: 'هل في طريقة منهجية لتمييز التليف الرئوي عن الالتهاب الخلالي؟',
    askedAt: '2026-04-30T17:12:00.000Z',
    answered: false,
  },
  {
    id: 'q-3',
    studentName: 'أحمد عاطف',
    studentAvatar: null,
    courseId: 'c-103',
    courseTitle: 'الأشعة المقطعية للصدر',
    lessonTitle: 'بروتوكولات HRCT',
    question: 'متى نستخدم ال inspiration vs expiration بشكل أساسي؟',
    askedAt: '2026-04-30T11:38:00.000Z',
    answered: false,
  },
];

/* ============================== Earnings ============================== */

export const MOCK_EARNINGS_TIMELINE: EarningsMonth[] = [
  { month: '2025-11', amount: 168_400 },
  { month: '2025-12', amount: 192_800 },
  { month: '2026-01', amount: 224_100 },
  { month: '2026-02', amount: 211_500 },
  { month: '2026-03', amount: 248_900 },
  { month: '2026-04', amount: 283_500 },
];

export const MOCK_PAYOUTS: PayoutRecord[] = [
  {
    id: 'p-1',
    amount: 248_900,
    status: 'paid',
    method: 'تحويل بنكي · CIB',
    date: '2026-04-05T00:00:00.000Z',
  },
  {
    id: 'p-2',
    amount: 211_500,
    status: 'paid',
    method: 'تحويل بنكي · CIB',
    date: '2026-03-05T00:00:00.000Z',
  },
  {
    id: 'p-3',
    amount: 283_500,
    status: 'processing',
    method: 'تحويل بنكي · CIB',
    date: '2026-05-05T00:00:00.000Z',
  },
];

/* ============================== Students ============================== */

export const MOCK_STUDENTS: InstructorStudent[] = [
  {
    id: 's-1',
    name: 'نور عبدو',
    avatar: null,
    email: 'noor.abdo@example.com',
    enrolledCoursesCount: 3,
    completedCoursesCount: 1,
    totalSpent: 3_697,
    joinedAt: '2025-12-04T08:00:00.000Z',
    averageProgress: 72,
  },
  {
    id: 's-2',
    name: 'محمد إبراهيم',
    avatar: null,
    email: 'mohammed.ibrahim@example.com',
    enrolledCoursesCount: 2,
    completedCoursesCount: 0,
    totalSpent: 2_498,
    joinedAt: '2026-02-19T08:00:00.000Z',
    averageProgress: 38,
  },
  {
    id: 's-3',
    name: 'سارة طارق',
    avatar: null,
    email: 'sara.tarek@example.com',
    enrolledCoursesCount: 4,
    completedCoursesCount: 2,
    totalSpent: 4_596,
    joinedAt: '2025-10-11T08:00:00.000Z',
    averageProgress: 88,
  },
  {
    id: 's-4',
    name: 'خالد جمال',
    avatar: null,
    email: 'khaled.gamal@example.com',
    enrolledCoursesCount: 1,
    completedCoursesCount: 0,
    totalSpent: 999,
    joinedAt: '2026-04-30T08:00:00.000Z',
    averageProgress: 9,
  },
  {
    id: 's-5',
    name: 'ريم شعبان',
    avatar: null,
    email: 'reem.shaaban@example.com',
    enrolledCoursesCount: 2,
    completedCoursesCount: 1,
    totalSpent: 2_498,
    joinedAt: '2026-01-22T08:00:00.000Z',
    averageProgress: 64,
  },
  {
    id: 's-6',
    name: 'عمر السيد',
    avatar: null,
    email: 'omar.elsayed@example.com',
    enrolledCoursesCount: 5,
    completedCoursesCount: 3,
    totalSpent: 5_795,
    joinedAt: '2025-08-08T08:00:00.000Z',
    averageProgress: 81,
  },
];
